name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gcc
      run: apt -y install gcc
    - name: compile
      run: gcc -o ./accurate_battery --static ./accurate_battery.c
