name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GCC
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-gcc@d04208cef6e985db0830428975fc2ab3f28d89a1
      uses: egor-tensin/setup-gcc@v1
      with:
        # GCC version to install
        version: default
        # Target platform
        platform: arm64
        # Install Cygwin packages
        cygwin: 0
        # Set up cc/gcc/c++/g++ executables
        cc: 1
        # On Cygwin, replace executable symlinks with hardlinks
        hardlinks: 0
    - name: compile
      run: gcc -o ./accurate_battery --static ./accurate_battery.c
